version: '3.3'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    container_name: famiphoto_frontend
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

