version: '3.3'
services:
  builder:
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    container_name: famiphoto_frontend-builder
    platform: linux/amd64
    tty: true
    volumes:
      - ./:/workspace/famiphoto_frontend
