#!/bin/sh

# インストール前の処理

getent group famiphoto || groupadd famiphoto
id -u famiphoto > /dev/null 2>&1;
if [ $? -eq 1 ]; then
  useradd famiphoto -g famiphoto
fi

mkdir -p /var/log/famiphoto
chown -R famiphoto:famiphoto /var/log/famiphoto

mkdir -p /var/www/famiphoto
chown -R famiphoto:famiphoto /var/www/famiphoto
